version: "3"

services:
  backend:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    working_dir: /go/src/chat2pay
    container_name: backend
    hostname: backend
    networks:
      - code-network
    volumes:
      - ../config/yaml:/go/src/chat2pay/config/yaml
    ports:
      - 8081:8081

networks:
  code-network:
    driver: bridge
